name: "Setup Varnish HTTP Cache"
description: "Setup Varnish HTTP Cache"
author: "varnishcache-friends"
inputs:
  version:
    description: "Varnish HTTP Cache version to use"
    required: true
    default: "master"
runs:
  using: composite
  steps:
    - name: Install dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libedit-dev \
          python3-docutils \
          python3-sphinx
    - name: Install dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew update
        brew install \
          docutils \
          sphinx-doc
    - name: Determine ref
      id: refs
      shell: bash
      run: |
        refname=${{ inputs.version }}
        if [[ $refname =~ [0-9]+\.[0-9]+\.[0-9]+ ]]; then
          refname="varnish-$refname"
        fi
        echo "REFNAME=$refname" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v3
      with:
        repository: "varnishcache/varnish-cache"
        ref: ${{ steps.refs.outputs.REFNAME }}
    - name: Build and install varnish-cache
      shell: bash
      run: |
        ./autogen.sh
        ./configure
        make
        sudo make install
        sudo ldconfig
