name: "Setup Varnish HTTP Cache"
description: "Setup Varnish HTTP Cache"
author: "varnishcache-friends"
inputs:
  version:
    description: "Varnish HTTP Cache version to use"
    required: true
    default: "master"
runs:
  using: composite
  steps:
    - name: Unsupported platform
      if: runner.os == 'Windows'
      shell: bash
      run: |
        echo "unsupported platform"
        exit 1
    - name: Install dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libedit-dev \
          python3-docutils \
          python3-sphinx
    - name: Install dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew update
        brew install \
          automake \
          docutils \
          sphinx-doc
        echo "/usr/local/opt/sphinx-doc/bin" >> $GITHUB_PATH
    - name: Determine refname
      id: refs
      shell: bash
      run: |
        refname=${{ inputs.version }}
        if [[ $refname =~ [0-9]+\.[0-9]+\.[0-9]+ ]]; then
          refname="varnish-$refname"
        fi
        echo "REFNAME=$refname" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v3
      with:
        repository: "varnishcache/varnish-cache"
        ref: ${{ steps.refs.outputs.REFNAME }}
    - name: Build and install varnish-cache
      shell: bash
      run: |
        ./autogen.sh
        ./configure
        make
        sudo make install
        sudo ldconfig
    - name: Cleanup
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get purge -y \
          libedit-dev \
          python3-docutils \
          python3-sphinx
    - name: Cleanup
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew uninstall \
          automake \
          docutils \
          sphinx-doc
